CREATE DATABASE IF NOT EXISTS audit_log DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE audit_log;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    role VARCHAR(16) NOT NULL
);
